name: CMake build

on:
  push:
    branches: ["**"]
    tags: ["*"]
  pull_request:
    branches: ["**"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        qt: [qt6, qt5]

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        if [ "${{ matrix.qt }}" = "qt6" ]; then
          sudo apt-get install -y qt6-base-dev;
        else
          sudo apt-get install -y qtbase5-dev;
        fi

    - name: Install Qt (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install -y qt6 || choco install -y qt5-default

    - name: Configure CMake
      run: |
        if [ "${{ matrix.qt }}" = "qt6" ]; then
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DQT_MAJOR_VERSION=6;
        else
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DQT_MAJOR_VERSION=5;
        fi

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
