name: CMake build

on:
  push:
    branches: ["**"]
    tags: ["*"]
  pull_request:
    branches: ["**"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        qt: [qt6, qt5]

    continue-on-error: ${{ matrix.os == 'windows-latest' }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        if [ "${{ matrix.qt }}" = "qt6" ]; then
          sudo apt-get install -y qt6-base-dev;
        else
          sudo apt-get install -y qtbase5-dev;
        fi

    - name: Install Qt (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install -y qt6 || choco install -y qt5-default

    - name: Configure CMake (Qt6)
      if: matrix.qt == 'qt6'
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DQT_MAJOR_VERSION=6

    - name: Configure CMake (Qt5)
      if: matrix.qt == 'qt5'
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DQT_MAJOR_VERSION=5

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run CPack (create Debian package)
      if: runner.os == 'Linux'
      run: |
        cd ${{github.workspace}}/build
        cpack -G DEB

    - name: Upload Debian package
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: debian-package
        path: ${{github.workspace}}/build/*.deb
